name: "Tox CI"
description: "Run tox"
inputs:
  environment:
    default: ""
    description: "The tox environment to invoke"
  python-version:
    description: "The Python version to use"
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: requirements*/*.txt

    - run: pip install tox
      shell: bash

    - name: cache mypy
      if: ${{ inputs.environment == 'typing' }}
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ./.mypy_cache
        key: mypy|${{ hashFiles('pyproject.toml') }}

    - run: tox run -e $TOX_ENV
      shell: bash
      env:
        TOX_ENV: ${{ inputs.environment }}
